<?php
/**
 * This is a file automatically generated by the Mouf framework and contains
 * the list of config parameters of the application.
 *
 * Unless you know what you are doing, do not modify it, as it could be overwritten.
 */
		
return [];
